import type { Player } from "@/server/data/schemas"

export const mockPlayers: Player[] = [
  {
    id: 10909049,
    timestamp: "6/21/2026 21:26:12",
    discord: "crestive",
    badges: 3,
    timezone: "UTC-6",
    pronoun1: "he",
    pronoun2: "him",
    joinedDiscord: true,
    username: "Crestive",
    countryCode: "US",
    pronouns: "he/him",
    rank: 1523,
    bws: 1200,
  },
  {
    id: 2757689,
    timestamp: "6/21/2026 21:30:44",
    discord: "wanderio",
    badges: 0,
    timezone: "UTC+1",
    pronoun1: "she",
    pronoun2: "her",
    joinedDiscord: true,
    username: "Wanderio",
    countryCode: "DE",
    pronouns: "she/her",
    rank: 9812,
    bws: 8400,
  },
  {
    id: 7562902,
    timestamp: "6/21/2026 21:35:02",
    discord: "kehest",
    badges: 1,
    timezone: "UTC-5",
    pronoun1: "",
    pronoun2: "",
    joinedDiscord: true,
    username: "Kehest",
    countryCode: "CA",
    pronouns: null,
    rank: 4210,
    bws: 3600,
  },
  {
    id: 6797627,
    timestamp: "6/21/2026 21:40:19",
    discord: "aidinth",
    badges: 2,
    timezone: "UTC-8",
    pronoun1: "they",
    pronoun2: "them",
    joinedDiscord: true,
    username: "aidinth",
    countryCode: "US",
    pronouns: "they/them",
    rank: 640,
    bws: 500,
  },
  {
    id: 3178368,
    timestamp: "6/21/2026 21:44:51",
    discord: "cinnamontwist",
    badges: 0,
    timezone: "UTC+9",
    pronoun1: "she",
    pronoun2: "",
    joinedDiscord: false,
    username: "Cinnamon Twist",
    countryCode: "JP",
    pronouns: "she",
    rank: 22001,
    bws: 19000,
  },
  {
    id: 124493,
    timestamp: "6/21/2026 21:50:07",
    discord: "cookiezi",
    badges: 5,
    timezone: "UTC+9",
    pronoun1: "he",
    pronoun2: "him",
    joinedDiscord: true,
    username: "Cookiezi",
    countryCode: "KR",
    pronouns: "he/him",
    rank: 1,
    bws: 1,
  },
]
