import type { Staff } from "@/server/data/schemas"

export const mockStaff: Staff[] = [
  {
    id: 124493,
    timestamp: "6/21/2026 21:26:12",
    discord: "crestive",
    pronoun1: "he",
    pronoun2: "him",
    roles: ["Host", "Developer"],
    customLink: null,
    experience: "5 years running tournaments",
    timezone: "UTC-6",
    approved: true,
    username: "Crestive",
    countryCode: "US",
    pronouns: "he/him",
  },
  {
    id: 2757689,
    timestamp: "6/21/2026 21:30:44",
    discord: "wanderio",
    pronoun1: "she",
    pronoun2: "her",
    roles: ["Referee"],
    customLink: "https://twitter.com/wanderio",
    experience: "Referee since 2022",
    timezone: "UTC+1",
    approved: true,
    username: "Wanderio",
    countryCode: "DE",
    pronouns: "she/her",
  },
  {
    id: 7562902,
    timestamp: "6/21/2026 21:35:02",
    discord: "kehest",
    pronoun1: "",
    pronoun2: "",
    roles: ["Mappooler", "Referee"],
    customLink: null,
    experience: "Mappooling for 3 seasons",
    timezone: "UTC-5",
    approved: true,
    username: "Kehest",
    countryCode: "CA",
    pronouns: null,
  },
  {
    id: 6797627,
    timestamp: "6/21/2026 21:40:19",
    discord: "aidinth",
    pronoun1: "they",
    pronoun2: "them",
    roles: ["Streamer", "Commentator"],
    customLink: null,
    experience: "Casting since 2021",
    timezone: "UTC-8",
    approved: true,
    username: "aidinth",
    countryCode: "US",
    pronouns: "they/them",
  },
]
